### ISSUE TITLE
do you offer support?

### ISSUE THREAD

**Issue by Mesrine67** [CandrexDev/cc-hud#2]
can you give support with this minimap? cayo perico inclut ? https://flybandit.tebex.io/package/5924688

**Comment by AndreasKTZ** [comment]
@Mesrine67 Any custom map can be used with cc-hud. Just make sure you ensure cc-hud before the map resource.

**Comment by Mesrine67** [comment]
![image](https://github.com/CandrexDev/cc-hud/assets/89279156/33f263c4-f4ec-426b-82de-c7c8c2f9ae58)
![image](https://github.com/CandrexDev/cc-hud/assets/89279156/4be6836e-3894-4563-b4eb-2e357d3b9f89)
watch i get this with cayo perico
